import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Building2, GraduationCap, MapPin, Plus, Trash2, UserCheck, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../../../components/Button/Button.tsx';
import { Input } from '../../../components/Form/Input.tsx';
import { SchoolsMap } from '../../../components/Map/SchoolsMap.tsx';
import { useAuth } from '../../../context/auth/useAuth.ts';
import { useSchool } from '../../../context/school/useSchool.ts';
import { useUser } from '../../../context/user/useUser.ts';
import { Role, ApplicationStatus } from '../../../types/common.types.ts';
import { ROUTES } from '../../../router/routes.config.ts';
import styles from './SchoolAdminWorkspace.module.css';

type WorkspaceView = 'dashboard' | 'profile' | 'branches' | 'classrooms' | 'posts' | 'applications' | 'educationHeads';
const roleNames: Record<Role, string> = { ADMIN: 'Administrator', EDUCATION_HEAD: 'Education head', MENTOR: 'Mentor', STUDENT: 'Student', SUPER_ADMIN: 'Platform administrator' };

export function SchoolAdminWorkspace({ view }: { view: WorkspaceView }) {
  const { user } = useAuth(); const schoolId = user?.schoolId || '';
  const school = useSchool(); const userStore = useUser();
  const [notice, setNotice] = useState(''); const [branchName, setBranchName] = useState(''); const [branchAddress, setBranchAddress] = useState(''); const [latitude, setLatitude] = useState('9.03'); const [longitude, setLongitude] = useState('38.74'); const [classroomName, setClassroomName] = useState(''); const [postRole, setPostRole] = useState<Role>(Role.MENTOR); const [postDescription, setPostDescription] = useState(''); const [mentorByClassroom, setMentorByClassroom] = useState<Record<string, string>>({}); const [profileName, setProfileName] = useState(''); const [profileDescription, setProfileDescription] = useState('');
  useEffect(() => { if (!schoolId) return; void school.loadSchoolById(schoolId); void school.loadBranches(schoolId); void school.loadClassrooms(schoolId); void school.loadStaffPosts(schoolId); void school.loadStaffApplications(schoolId); void userStore.loadUsers(); }, [schoolId]);
  useEffect(() => { if (school.activeSchool) { setProfileName(school.activeSchool.name); setProfileDescription(school.activeSchool.description || ''); } }, [school.activeSchool]);
  useEffect(() => { school.classrooms.forEach((item) => { void school.loadClassroomMentors(item.id); }); }, [school.classrooms]);
  const users = userStore.users?.data || []; const mentors = users.filter((item) => item.schoolId === schoolId && item.role === Role.MENTOR); const heads = users.filter((item) => item.schoolId === schoolId && item.role === Role.EDUCATION_HEAD); const userName = (id: string) => { const found = users.find((item) => item.id === id); return found ? `${found.firstName} ${found.lastName}` : 'Applicant'; };
  const linkedMentors = useMemo(() => new Map(school.classroomMentors.map((link) => [link.classroomId, link.mentorId])), [school.classroomMentors]);
  const complete = (message: string) => setNotice(message);
  const addBranch = async (event: FormEvent) => { event.preventDefault(); await school.addBranch(schoolId, { name: branchName, address: branchAddress, latitude: Number(latitude), longitude: Number(longitude) }); setBranchName(''); setBranchAddress(''); complete('Branch added to the map.'); };
  const addClassroom = async (event: FormEvent) => { event.preventDefault(); await school.addClassroom(schoolId, classroomName); setClassroomName(''); complete('Classroom created. Assign a mentor below.'); };
  const addPost = async (event: FormEvent) => { event.preventDefault(); await school.addStaffPost(schoolId, postRole, postDescription); setPostDescription(''); complete('Staff opening is live.'); };
  const assignMentor = async (classroomId: string) => { const mentorId = mentorByClassroom[classroomId]; if (!mentorId) return; await school.assignClassroomMentor(classroomId, mentorId); complete('Mentor assigned to classroom.'); };
  const updateProfile = async (event: FormEvent) => { event.preventDefault(); await school.updateSchoolInfo(schoolId, { name: profileName, description: profileDescription }); complete('School profile saved.'); };
  const title: Record<WorkspaceView, string> = { dashboard: 'School control room', profile: 'School profile', branches: 'Branch management', classrooms: 'Classrooms', posts: 'Staff openings', applications: 'Staff applications', educationHeads: 'Education heads' };
  return <main className={styles.page}><div className={styles.inner}><header className={styles.header}><div><p className={styles.kicker}>ShumShufer / {school.activeSchool?.name || 'School workspace'}</p><h1>{title[view]}</h1></div>{notice && <span className={styles.notice}>{notice}</span>}</header>
  {view === 'dashboard' && <section className={styles.dashboard}><div className={styles.metrics}><Metric icon={<Users />} label="Mentors" value={String(mentors.length)} /><Metric icon={<GraduationCap />} label="Classrooms" value={String(school.classrooms.length)} /><Metric icon={<MapPin />} label="Branches" value={String(school.branches.length)} /><Metric icon={<Building2 />} label="Open roles" value={String(school.staffPosts.filter((post) => post.status === 'OPEN').length)} /></div><div className={styles.grid}><section className={styles.card}><h2>Run the next school action</h2><div className={styles.actionList}><Link to={ROUTES.admin.classrooms}><GraduationCap size={18} /> Create a classroom and assign a mentor</Link><Link to={ROUTES.admin.branches}><MapPin size={18} /> Keep branch locations current</Link><Link to={ROUTES.admin.staffPosts}><Users size={18} /> Open a staff role</Link></div></section><section className={styles.card}><h2>Branch coverage</h2><SchoolsMap schools={school.activeSchool ? [school.activeSchool] : []} branches={school.branches} variant="profile" /></section></div></section>}
  {view === 'profile' && <form className={styles.formCard} onSubmit={updateProfile}><Input label="School name" value={profileName} onChange={(event) => setProfileName(event.target.value)} required /><label className={styles.textField}>Description<textarea value={profileDescription} onChange={(event) => setProfileDescription(event.target.value)} /></label><Button type="submit">Save school profile</Button></form>}
  {view === 'branches' && <section className={styles.grid}><form className={styles.formCard} onSubmit={addBranch}><h2>Add Addis Ababa branch</h2><Input label="Branch name" value={branchName} onChange={(event) => setBranchName(event.target.value)} required /><Input label="Address" value={branchAddress} onChange={(event) => setBranchAddress(event.target.value)} required /><div className={styles.twoCol}><Input label="Latitude" type="number" step="any" value={latitude} onChange={(event) => setLatitude(event.target.value)} required /><Input label="Longitude" type="number" step="any" value={longitude} onChange={(event) => setLongitude(event.target.value)} required /></div><Button type="submit"><Plus size={16} /> Add branch</Button></form><section className={styles.card}><SchoolsMap schools={school.activeSchool ? [school.activeSchool] : []} branches={school.branches} variant="profile" /></section><section className={styles.listCard}>{school.branches.map((branch) => <article key={branch.id} className={styles.row}><div><strong>{branch.name}</strong><span>{branch.address}</span></div><Button variant="ghost" size="sm" onClick={() => void school.removeBranch(branch.id)}><Trash2 size={16} /></Button></article>)}</section></section>}
  {view === 'classrooms' && <section className={styles.grid}><form className={styles.formCard} onSubmit={addClassroom}><h2>Create a classroom</h2><Input label="Classroom name" value={classroomName} onChange={(event) => setClassroomName(event.target.value)} placeholder="e.g. June weekday theory" required /><Button type="submit"><Plus size={16} /> Create classroom</Button></form><section className={styles.listCard}>{school.classrooms.map((classroom) => { const currentMentor = linkedMentors.get(classroom.id); return <article key={classroom.id} className={styles.classroom}><div><strong>{classroom.name}</strong><span>{currentMentor ? `Mentor: ${userName(currentMentor)}` : 'No mentor assigned'}</span></div><div className={styles.inlineAction}>{!currentMentor && <><select value={mentorByClassroom[classroom.id] || ''} onChange={(event) => setMentorByClassroom((previous) => ({ ...previous, [classroom.id]: event.target.value }))}><option value="">Assign mentor</option>{mentors.map((mentor) => <option key={mentor.id} value={mentor.id}>{mentor.firstName} {mentor.lastName}</option>)}</select><Button size="sm" onClick={() => void assignMentor(classroom.id)}>Assign</Button></>}{currentMentor && <Button variant="ghost" size="sm" onClick={() => void school.removeClassroomMentor(classroom.id, currentMentor)}><X size={16} /> Remove mentor</Button>}<Button variant="ghost" size="sm" onClick={() => void school.removeClassroom(classroom.id)}><Trash2 size={16} /></Button></div></article>; })}</section></section>}
  {view === 'posts' && <section className={styles.grid}><form className={styles.formCard} onSubmit={addPost}><h2>Post an opening</h2><label className={styles.textField}>Role<select value={postRole} onChange={(event) => setPostRole(event.target.value as Role)}><option value={Role.MENTOR}>Mentor</option><option value={Role.EDUCATION_HEAD}>Education head</option></select></label><label className={styles.textField}>Role description<textarea value={postDescription} onChange={(event) => setPostDescription(event.target.value)} required /></label><Button type="submit"><Plus size={16} /> Publish opening</Button></form><section className={styles.listCard}>{school.staffPosts.map((post) => <article key={post.id} className={styles.row}><div><strong>{roleNames[post.role]}</strong><span>{post.description}</span></div><div className={styles.inlineAction}><span className={styles.badge}>{post.status}</span><Button variant="ghost" size="sm" onClick={() => void school.removeStaffPost(post.id)}><Trash2 size={16} /></Button></div></article>)}</section></section>}
  {view === 'applications' && <section className={styles.listCard}>{school.staffApplications.map((application) => <article key={application.id} className={styles.row}><div><strong>{userName(application.applicantId)}</strong><span>Applied for {roleNames[school.staffPosts.find((post) => post.id === application.postId)?.role || Role.MENTOR]}</span></div><div className={styles.inlineAction}><span className={styles.badge}>{application.status}</span>{application.status === ApplicationStatus.PENDING && <><Button size="sm" onClick={() => void school.updateStaffApplication(application.id, ApplicationStatus.ACCEPTED)}>Accept</Button><Button size="sm" variant="secondary" onClick={() => void school.updateStaffApplication(application.id, ApplicationStatus.REJECTED)}>Decline</Button></>}</div></article>)}</section>}
  {view === 'educationHeads' && <section className={styles.grid}><section className={styles.listCard}><h2>Assigned education heads</h2>{heads.map((head) => <article key={head.id} className={styles.row}><div><strong>{head.firstName} {head.lastName}</strong><span>{head.email}</span></div><Button variant="ghost" size="sm" onClick={() => void school.removeEducationHead(schoolId, head.id)}><X size={16} /> Remove</Button></article>)}</section><section className={styles.listCard}><h2>Eligible mentors</h2>{mentors.map((mentor) => <article key={mentor.id} className={styles.row}><div><strong>{mentor.firstName} {mentor.lastName}</strong><span>{mentor.email}</span></div><Button size="sm" onClick={() => void school.assignEducationHead(schoolId, mentor.id)}><UserCheck size={16} /> Assign</Button></article>)}</section></section>}
  </div></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <article className={styles.metric}><span>{icon}</span><strong>{value}</strong><p>{label}</p></article>; }
